spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddal-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
jwt:
  secret: ericsecret